on:
  issues:
    types: [opened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: issus2posts
        uses: wayou/turn-issues-to-posts-action@v1
        with:
          branch: "master"
          dir: "_posts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          created_at: ${{ github.event.issue.created_at }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          actor: ${{ github.actor }}
      - run: echo markdown-file ${{ steps.issus2posts.outputs.markdown-file }}
        shell: bash
